package com.kie_space.kie_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TaskDTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "status")
	private java.lang.String status;

	public TaskDTO() {
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public TaskDTO(java.lang.String status) {
		this.status = status;
	}

}